analytics: {}
color:
  brandColors:
    - '#A8B0C0'
    - '#706818'
    - '#9098A8'
    - '#B80820'
    - '#E0D898'
  brandStrength: 1
  lightness: 0.134009
  rhythmicContrast: 0.163162
  saturation: 0
cta: {}
layout_spectrum: 0.943693
name: PINK
opengraph: {}
purpose: {}
typography_spectrum: 0.948198
