analytics: {}
color:
  brandColors:
    - '#E0D8E0'
    - '#711438'
    - '#C880A0'
    - '#E05088'
    - '#F8B8C8'
  brandStrength: 1
  lightness: 0.618244
  rhythmicContrast: 0.920045
  saturation: 0.512388
cta: {}
layout_spectrum: 0.932432
name: PINK
opengraph: {}
purpose: {}
typography_spectrum: 0.11036
